name: build
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
         https://github.com/loongson/build-tools/releases/download/2023.08.08/x86_64-cross-tools-loongarch64-binutils_2.41-gcc_13.2.0.tar.xz
         tar -vxf x86_64-cross-tools-loongarch64-binutils_2.41-gcc_13.2.0.tar.xz -C /opt
      - run: |
         export PATH=/opt/cross-tools/bin:$PATH
         export PACKAGES_PATH=$PWD/edk2:$PWD/edk2-platforms:$PWD/edk2-non-osi
         export GCC5_LOONGARCH64_PREFIX=loongarch64-unknown-linux-gnu-
         . edk2/edksetup.sh
         make -C edk2/BaseTools
         build --buildtarget=RELEASE --tagname=GCC5 --arch=LOONGARCH64  --platform=Platform/Loongson/LoongArchQemuPkg/Loongson.dsc
      - uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: Build/LoongArchQemu/RELEASE_GCC5/FV/*.fd
